---
# The domain name of the HomeLab.
domain: "homelab"

# The id that will be used to retrieve the proxmox's root password saved in the Secret Manager. It will be the same for all hosts.
proxmox_root_password_id: "proxmox-root-password"

# The id that will be used to retrieve the proxmox's SMTP password saved in the Secret Manager. It will be the same for all hosts.
proxmox_smtp_password_id: "proxmox-smtp-password"

# The id that will be used to retrieve the Ansible user's password saved in the Secret Manager. It will be the same for all hosts.
ansible_password_id: "ansible-password"

# The user account that Ansible will use to connect and run commands into each host.
# ansible_user: "usr_ansible"

# The password that Ansible will use to connect and run commands into each host.
# ansible_password: "{{ lookup('pipe', 'secret-tool lookup password {{ ansible_password_id }}') }}"
