---
- name: "Removing dependencies that are no longer required and unnecessary packages from the cache"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    autoremove: true
    autoclean: true
