---
- name: "Waiting 10 seconds"
  ansible.builtin.pause:
    seconds: 10

- name: "Updating Postfix table management"
  # No native Ansible module exists for postmap.
  ansible.builtin.command: "postmap /etc/postfix/sasl_passwd"
  register: "postmap_output"
  changed_when: postmap_output.rc == 0

- name: "Restarting Postfix"
  ansible.builtin.service:
    name: "postfix"
    state: "restarted"

- name: "Rebuilding Aliases Database"
  # No native Ansible module exists for newaliases.
  ansible.builtin.command: "newaliases"
  register: "newaliases_output"
  changed_when: newaliases_output.rc == 0

- name: "Sending a test email"
  no_log: "{{ not (debug | default(false)) }}"
  community.general.mail:
    host: "{{ smtp_server }}"
    port: "{{ smtp_port }}"
    secure: "starttls"
    username: "{{ smtp_email | b64decode }}"
    password: "{{ smtp_password }}"
    from: "{{ smtp_email | b64decode }}"
    to: "{{ smtp_email | b64decode }}"
    subject: "Email from {{ inventory_hostname }}"
    body: "Just testing"

- name: "Restarting PVEProxy"
  ansible.builtin.service:
    name: "pveproxy"
    state: "restarted"
