---
- name: "Setting up the host machines"
  hosts: "Nodes"
  gather_facts: false

  pre_tasks:
    - name: "Ensure the fingerprint is present in the known_hosts file"
      ansible.builtin.include_tasks: "{{ path_debian_known_hosts_add_current }}"

    - name: "Gettings facts using the setup module"
      ansible.builtin.setup:

  roles:
    - "host_machines"
