---
- name: "Run the control machine role"
  ansible.builtin.import_playbook: "control_machine.yml"

- name: "Run the host machines role"
  ansible.builtin.import_playbook: "host_machines.yml"

- name: "Run the proxmox role"
  ansible.builtin.import_playbook: "proxmox.yml"
