---
# The password Ansible will use to run the scripts.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password local-user-password') }}"

# The password that Ansible will use when running sudo commands.
ansible_become_password: "{{ ansible_password }}"
