---
- name: Adding the IP and URL of each host into the hosts file
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    line: "{{ hostvars[item].ansible_host }} {{ item }}.{{ domain }} {{ item }}"
    state: "present"
  when: hostvars[item].ansible_host is defined
  loop: "{{ groups['Proxmox'] }}"
