---
- name: "Upgrading the packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: "safe"

- name: "Installing required packages"
  ansible.builtin.include_tasks: "{{ path_packages_apt }}"
  vars:
    packages:
      - {name: "pip"}
      - {name: "sshpass"}
      - {name: "libsecret-tools"}
      - {name: "python-is-python3"}
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.

- name: "Installing pip packages"
  ansible.builtin.include_tasks: "{{ path_packages_pip }}"
  vars:
    packages:
      - {name: "passlib"}
      - {name: "ansible"}
      - {name: "ansible-lint"}
