---
- name: "Installing required packages"
  ansible.builtin.include_tasks: "{{ path_packages_apt }}"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "pip"}
      - {name: "sshpass"}
      - {name: "libsecret-tools"}
      - {name: "python-is-python3"}

- name: "Installing pip packages"
  ansible.builtin.include_tasks: "{{ path_packages_pip }}"
  vars:
    packages:
      - {name: "passlib"}
      - {name: "ansible"}
      - {name: "ansible-lint"}
