---
- name: "Creating the HA groups"
  run_once: true
  ansible.builtin.command: "ha-manager groupadd '{{ item.name }}' --nodes '{{ item.nodes }}' --comment '{{ item.comment }}'"
  register: "create_ha_groups"
  changed_when: create_ha_groups.rc == 0
  failed_when: (create_ha_groups.rc != 0) and ' already defined' not in create_ha_groups.stderr
  loop: "{{ ha_groups }}"
