---
# - name: "Setting up email notification with Postfix"
#   ansible.builtin.import_tasks: "email-notification.yml"

# - name: "Removing the no subscription popup"
#   ansible.builtin.import_tasks: "subscription-popup.yml"

# - name: "Creating the cluster and join the nodes into it"
#   ansible.builtin.import_tasks: "cluster.yml"

# - name: "Setting up the network for all migrations in the cluster"
#   ansible.builtin.import_tasks: "migration-network.yml"

- name: "Formatting the HDD, SSD and NVME drives"
  ansible.builtin.import_tasks: "local-storage.yml"

# Do not uncomment unless you really want to destroy the cluster.
### - name: "Remove all nodes from the cluster"
###   ansible.builtin.import_tasks: "destroy-cluster.yml"
