---
- name: "Creating the roles"
  run_once: true
  ansible.builtin.command: "pveum roleadd {{ item.name }} -privs '{{ item.privileges }}'"
  register: "create_role"
  changed_when: create_role.rc == 0
  failed_when: (create_role.rc != 0) and ' already exists' not in create_role.stderr
  loop: "{{ permissions_roles }}"
