---
- name: "Removing the no subscription popup"
  ansible.builtin.replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: 'if \(\s*res === null \|\|\s*res === undefined \|\|\s*!res \|\|\s*res\.data\.status\.toLowerCase\(\) !== ''active''\s*\) \{'
    replace: "if (false) {"
    backup: true
  notify: "Restarting PVEProxy"
