---
- name: "Removing the no subscription popup"
  ansible.builtin.replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: if \(res === null \|\| res === undefined \|\| !res \|\| res\s+\.data\.status\.toLowerCase\(\) !== 'active'\) \{
    replace: "if (false) {"
    backup: true
  notify: "Restarting PVEProxy"
