---
- name: Removing the volume group {{ item.volume_group }}
  lvg:
    vg: "{{ item.volume_group }}"
    pvs: "/dev/{{ partition.1 }}"
    state: "absent"
    force: true

- name: Removing the physical volume
  ansible.builtin.command: "pvremove /dev/{{ partition.1 }}"
  register: "output"
  # failed_when: false
  failed_when: output.rc != 0
  changed_when: output.rc != 0
