---
# - name: debug {{ host.name }}
#   debug:
#     msg:
#       - "{{ host.name }}"
#       - "{{ host.key }}"

- name: Adding the fingerprint of host {{ host.name }} into the know_hosts file
  known_hosts:
    name: "{{ host.name }}"
    key: "{{ host.key }}"
    state: "present"
    # hash_host: yes
  ignore_errors: True
  when: host.name | length > 0 and host.key | length > 0
  register: output

# - name: debug
#   debug:
#     var: output
