---
- name: Adding the fingerprint of each host into the know_hosts file
  known_hosts:
    name: "{{ item }}.{{ domain }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa {{ item }}.{{ domain }},{{ hostvars[item].ansible_host }}') }}"
  loop: "{{ groups['Proxmox'] }}"
