---
- name: Adding the internal IP and url of all hosts into the 'hosts' file
  lineinfile:
    path: "/etc/hosts"
    line: "{{ hostvars[item].internal_ip }} {{ item }}.{{ domain }} {{ item }}"
    insertbefore: '^\s*$' #Empty line
    firstmatch: yes
    state: "present"
  when: ansible_hostname != item
  loop: "{{ groups['Proxmox'] }}"
