---
- name: Adding SMTP server, user name and password into the sasl_passwd file
  template:
    src: "../templates/sasl_passwd.j2"
    dest: "/etc/postfix/sasl_passwd"
    mode: "0600"
  notify: "Updating Postfix table management"

- name: Adding relayhost into the main.cf file
  lineinfile:
    path: "/etc/postfix/main.cf"
    regexp: "^relayhost ="
    line: "relayhost = {{ smtp_server }}:{{ smtp_port }}"
    state: "present"
  notify: "Restarting Postfix"

- name: Adding SASL authentication into the main.cf file
  blockinfile:
    path: "/etc/postfix/main.cf"
    block: |
      smtp_use_tls = yes
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options = noanonymous
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
      smtp_tls_session_cache_database = btree:/var/lib/postfix/smtp_tls_session_cache
      smtp_tls_session_cache_timeout = 3600s
    marker: "# {mark} SASL authentication"
  notify: "Restarting Postfix"

  # It is a bug on debian.
- name: Removing the symlink for the makedefs.out
  file:
    path: "/etc/postfix/makedefs.out"
    state: "absent"
  notify: "Restarting Postfix"
