---
- name: Checking if the cluster already exists
  stat:
    path: "/etc/pve/corosync.conf"
  register: corosync

- name: Creating cluster (only on {{ cluster_master_node }})
  command: "pvecm create {{ cluster_name }} -link0 address={{ internal_ip }},priority=0 -link1 address={{ management_ip }},priority=1"
  register: create_cluster
  when: ansible_hostname == cluster_master_node and not corosync.stat.exists

- name: Adding the fingerprint of the hosts into the know_hosts file
  include_tasks: "04-cluster-known-hosts.yml"
  when: ansible_hostname != item
  loop: "{{ groups['Proxmox'] }}"

- name: Adding nodes to cluster
  throttle: 1
  expect:
    command: "pvecm add {{ hostvars[cluster_master_node].management_ip }} -link0 address={{ internal_ip }},priority=0 -link1 address={{ management_ip }},priority=1 -force"
    responses:
      'Please enter': "{{ proxmox_root_password }}"
      'Are you sure': "yes"
    echo: yes
  no_log: true
  register: join_cluster
  when: ansible_hostname != cluster_master_node and not corosync.stat.exists

- name: Print the join_cluster
  debug:
    msg: 
      - "{{ create_cluster }}"
      - "{{ join_cluster }}"