---
- name: Checking if the cluster already exists
  stat:
    path: "/etc/pve/corosync.conf"
  register: "corosync"

- name: Creating cluster (only on {{ cluster_master_node }})
  command: "pvecm create {{ cluster_name }} -link0 address={{ cluster_ip }},priority=0"
  register: "create_cluster"
  when: ansible_hostname == cluster_master_node and not corosync.stat.exists

- name: Adding the fingerprint of all other hosts into the know_hosts file
  include_tasks: "04.1-cluster-known-hosts.yml"
  vars:
    ansible_become: false
  when: ansible_hostname != item
  loop: "{{ groups['Proxmox'] }}"

- name: Adding nodes to cluster
  throttle: 1
  expect:
    command: "pvecm add {{ hostvars[cluster_master_node].wan_management_ip }} -link0 address={{ cluster_ip }},priority=0 -force"
    responses:
      'Please enter': "{{ proxmox_root_password }}"
      'Are you sure': "yes"
    echo: yes
  timeout: 30
  no_log: true
  register: "join_cluster"
  when: ansible_hostname != cluster_master_node and not corosync.stat.exists
