---
- name: Removing a LVM-Thin from the cluster
  shell: "pvesm remove {{ item.name }}"
  register: lvmthin_output
  changed_when: lvmthin_output.rc == 0
  failed_when: (lvmthin_output.rc != 0) and ' does not exist' not in lvmthin_output.stderr

- name: Removing the logical volume {{ item.logical_volume }}
  lvol:
    thinpool: "{{ item.logical_volume }}"
    vg: "{{ item.volume_group }}"
    state: "absent"
    force: yes

- name: Getting the name of the primary partition of the disk
  shell: "lsblk -nr {{ device }} | grep part | cut -d' ' -f1"
  register: "disk_partitions"
  loop: "{{ item.devices }}"
  loop_control:
    loop_var: "device"
  changed_when: false

- name: Removing volume groups and logical volume
  include_tasks: "XX-02-remove-local-storage-partition.yml"
  loop: "{{ disk_partitions.results | subelements('stdout_lines') }}"
  loop_control:
    loop_var: "partition"
    label: "/dev/{{ partition.1 }}"

- name: Read device information (always use unit when probing)
  parted:
    device: "{{ device }}"
    unit: "MiB"
  register: "device_info"
  loop: "{{ item.devices }}"
  loop_control:
    loop_var: "device"

- name: Removing all partitions from disk
  parted:
    device: "{{ partition.0.disk.dev }}"
    number: "{{ partition.1.num }}"
    state: "absent"
  loop: "{{ device_info.results | subelements('partitions') }}"
  loop_control:
    loop_var: "partition"
    label: "{{ partition.0.disk.dev }}"

- name: Initializing disk with GPT
  shell: /bin/echo -e "d\no\nY\nw\nY\n" | gdisk "{{ device }}"
  loop: "{{ item.devices }}"
  loop_control:
    loop_var: "device"
