---
- name: Checking if the cluster already exists
  stat:
    path: "/etc/pve/corosync.conf"
  register: corosync

- name: Removing nodes from the cluster
  command: "pvecm delnode {{ item }}"
  when: ansible_hostname == cluster_master_node and ansible_hostname != item and corosync.stat.exists
  loop: "{{ groups['Proxmox'] }}"
  failed_when: false

- name: Destroying the cluster
  shell: "{{ item }}"
  loop:
    - "systemctl stop pvestatd"
    - "systemctl stop pvedaemon"
    - "systemctl stop pve-cluster"
    - "systemctl stop corosync"
    - "pmxcfs -l"
    - "sqlite3 /var/lib/pve-cluster/config.db \"delete from tree where name = 'corosync.conf';\""
    - "rm -f /var/lib/pve-cluster/.pmxcfs.lockfile"
    - "rm -f /etc/pve/corosync.conf"
    - "rm -rf /etc/corosync/*"
    - "rm -rf /var/lib/corosync/*"
    - "killall pmxcfs"
    - "systemctl start pve-cluster"
    - "systemctl restart pveproxy"
    - "systemctl start pvedaemon"
    - "systemctl start pvestatd"
    - "pvecm updatecerts"
  failed_when: false

- name: Removing nodes from the Web UI
  command: "rm -rf /etc/pve/nodes/{{ item }}"
  when: ansible_hostname != item
  loop: "{{ groups['Proxmox'] }}"
  failed_when: false
