---
- name: Removing the ZFS pool from the cluster
  command: "pvesm remove {{ zfs_pool_name }}"
  register: "output_remove"
  changed_when: output_remove.rc == 0
  failed_when: (output_remove.rc != 0) and ' does not exist' not in output_remove.stderr

- name: Destroying the ZFS pool
  command: "zpool destroy {{ zfs_pool_name }}"

- name: Read device information (always use unit when probing)
  parted:
    device: "{{ device }}"
    unit: "MiB"
  register: "device_info"
  loop: "{{ item.devices }}"
  loop_control:
    loop_var: "device"

- name: Removing all partitions from disk
  parted:
    device: "{{ partition.0.disk.dev }}"
    number: "{{ partition.1.num }}"
    state: "absent"
  loop: "{{ device_info.results | subelements('partitions') }}"
  loop_control:
    loop_var: "partition"
    label: "{{ partition.0.disk.dev }}"

- name: Initializing disk with GPT
  shell: /bin/echo -e "d\no\nY\nw\nY\n" | gdisk "{{ device }}"
  loop: "{{ item.devices }}"
  loop_control:
    loop_var: "device"
