---
- name: Removing the pve-enterprise repository from sources list
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
    state: absent

- name: Adding the pve-no-subscription repository into sources list
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes

- name: Removing unnecessary packages from the cache
  apt:
    autoclean: yes

- name: Updating apt repository and cache
  apt:
    update_cache: yes

- name: Installing required packages
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    - "sudo" # To enable elevated command.
    - "python3-pip" # To enable ansible scripts.
    - "systemd-timesyncd" # To enable time synchronization.
    - "ethtool" # To enable Wake-on-Lan.
    - "libsasl2-modules" # Necessary to Postfix.
    - "ifupdown2" # To enable make changes on the network configuration and don't require server reboot.
    - "parted" # To format hard disks (HDD, SSD and NVME).
    - "qrencode" # To enable two-factor authentication (2FA)

- name: Installing pip packages
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - "pip" # To install other python applications.
    - "proxmoxer" # To enable ansible scripts.
    - "requests" # To enable ansible scripts.
    - "pexpect" # To enable ansible scripts that use the expect module.

- name: Upgrading all packages
  apt:
    upgrade: dist

- name: Checking if a reboot is needed
  stat: 
    path: "/var/run/reboot-required"
    get_md5: "no"
  register: reboot_required

- name: Rebooting the host if kernel was updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates."
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists
