---
- name: Creating a random password with {{ ansible_password_size }} characters
  run_once: true
  delegate_to: "{{ groups['ControlMachine'][0] }}"
  set_fact:    
    usr_ansible_password: "{{ lookup('pipe', 'openssl rand -base64 {{ ansible_password_size }} | tr -d \"=+/\" | colrm {{ ansible_password_size + 1 }}') }}"

- name: Creating the Ansible user account
  user:
    name: "usr_ansible"
    comment: "Ansible User"
    password: "{{ usr_ansible_password | password_hash('sha512') }}"
    update_password: "on_create"
    shell: "/bin/bash"
    groups: 
      - "sudo"
    state: "present"
  register: creating_user_output

- name: Saving the password in the secret manager
  run_once: true
  delegate_to: "{{ groups['ControlMachine'][0] }}"
  import_tasks: "roles/common/tasks/passwords/add.yml"
  vars:
    password_id : "{{ ansible_password_id }}"
    password: "{{ usr_ansible_password }}"
  when: not creating_user_output.failed and creating_user_output.changed
  no_log: true
