---
- name: Copying the network config file
  template:
    src: "network-{{ template_network_type }}.j2"
    dest: "/etc/network/interfaces"
  register: "network_output"

- name: Renaming network cards to start with eth0-ethX
  lineinfile:
    path: "/etc/default/grub"
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
  register: "network_rename_output"
  notify:
    - "Generating Grub File"
    - "Rebooting Server"

- name: Restarting network
  service:
    name: "networking"
    state: "restarted"
  poll: 0
  async: 10
  when: not network_rename_output.changed and network_output.changed

- name: Wait for the network device to reload
  wait_for_connection:
    delay: 1
  when: not network_rename_output.changed and network_output.changed
