---
- name: Copying the empty 99-default.link file to override the default configuration
  copy:
    src: "99-default.link"
    dest: "/etc/systemd/network/"

- name: Copying the .link rule file to inform the OS to always put the same name in the network cards based on the MAC address
  template:
    src: "network-mac-bind.j2"
    dest: "/etc/systemd/network/10-{{ item.nic_name }}.link"
  vars:
    mac_address: "{{ item.mac_address }}"
    nic_name: "{{ item.nic_name }}"
  loop: "{{ mac_bind }}"
  register: "network_rename_output"

- name: Copying the network config file
  template:
    src: "network-{{ template_network_type }}.j2"
    dest: "/etc/network/interfaces"
  register: "network_config_file_output"

- name: Rebooting the host because the name of some network adapter has changed
  reboot:
    msg: "Reboot initiated by Ansible because the name of some network adapter has changed."
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: "whoami"
  when: network_rename_output.changed

- name: Restarting network
  service:
    name: "networking"
    state: "restarted"
  poll: 0
  async: 10
  when: network_config_file_output.changed and not network_rename_output.changed

- name: Wait for the network device to reload
  wait_for_connection:
    delay: 1
  when: network_config_file_output.changed and not network_rename_output.changed
