---
# The user that will be used to connect on each host.
ansible_user: "root"

# At this point we don't have a SSH Keypair yet. So it is necessary to connect using the root's password.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + proxmox_root_password_id) }}"
