---
# The user account that Ansible will use to connect and run commands into each host.
ansible_user: "usr_ansible"

# The password that Ansible will use to connect and run commands into each host.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + ansible_password_id) }}"

# The password that Ansible will use when running sudo commands.
ansible_become_password: "{{ ansible_password }}"
