---
# The name of the root user used in Proxmox.
proxmox_root_user: "root"

# The password of the root user used in Proxmox.
proxmox_root_password: "{{ lookup('pipe', 'secret-tool lookup password ' + proxmox_root_password_id) }}"

# The user that will be used to connect on each host.
ansible_user: "{{ proxmox_root_user }}"

# At this point we don't have a SSH Keypair yet. So it is necessary to connect using the root's password.
ansible_password: "{{ proxmox_root_password }}"

# The size of the password that will be created.
ansible_password_size: 30

# All servers are located in Aracaju - Brazil. Maceio is the closest city.
timezone: "America/Maceio"

# This is a DNS for the Fortigate NTP server.
ntp_service: "chrony"
ntp_servers:
  - {line: "pool 2.debian.pool.ntp.org iburst", state: "absent"}
  - {line: "pool ntp-pool.lan.homelab iburst", state: "present"}
