---
- name: "Running the control machine playbook"
  ansible.builtin.import_playbook: "01-control_machine.yml"

- name: "Running the host machines playbook"
  ansible.builtin.import_playbook: "02-host_machines.yml"

- name: "Running the proxmox playbook"
  ansible.builtin.import_playbook: "03-proxmox.yml"

- name: "Running the update playbook"
  ansible.builtin.import_playbook: "04-update.yml"
