---
# The user account that Ansible will use to connect and run commands into each host.
ansible_user: "usr_ansible"

# The password that Ansible will use to connect and run commands into each host.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + ansible_password_id) }}"

# The password that Ansible will use when running sudo commands.
ansible_become_password: "{{ ansible_password }}"

# The password of the root user used in Proxmox.
proxmox_root_password: "{{ lookup('pipe', 'secret-tool lookup password ' + proxmox_root_password_id) }}"

smtp_server: "smtp.gmail.com"
smtp_port: "587"
smtp_email: "bHNhbXBhaW93ZWJAZ21haWwuY29t"
smtp_password: "{{ lookup('pipe', 'secret-tool lookup password ' + proxmox_smtp_password_id) }}"

# The name of the HomeLab Cluster.
cluster_name: "HomeLab"
cluster_master_node: "{{ groups['Proxmox'][0] }}"
migration_network: "10.0.3.0/27"

resource_pools:
  - {name: "Production", comment: "Pool for the Production Virtual Machines."}
  - {name: "Staging", comment: "Pool for the Staging Virtual Machines."}
  - {name: "Template", comment: "Pool for template images."}

# pve-docs/chapter-pveum.html#pveum_roles
permissions_roles:
  - {name: "Packer", privileges: "Datastore.AllocateSpace, Datastore.Audit,\
  Group.Allocate, Pool.Audit, Pool.Allocate, Sys.Audit, Sys.Modify,\
  VM.Allocate, VM.Audit, VM.Clone, VM.Config.CDROM, VM.Config.CPU,\
  VM.Config.Cloudinit, VM.Config.Disk, VM.Config.HWType, VM.Config.Memory,\
  VM.Config.Network, VM.Config.Options, VM.Console, VM.Monitor, VM.PowerMgmt"}
  - {name: "Terraform", privileges: "Datastore.AllocateSpace, Datastore.Audit,\
  Group.Allocate, Pool.Audit, Pool.Allocate, Sys.Audit, Sys.Console, Sys.Modify,\
  VM.Allocate, VM.Audit, VM.Clone, VM.Config.CDROM, VM.Config.CPU,\
  VM.Config.Cloudinit, VM.Config.Disk, VM.Config.HWType, VM.Config.Memory,\
  VM.Config.Network, VM.Config.Options, VM.Console, VM.Migrate, VM.Monitor, VM.PowerMgmt"}

ha_groups:
  - {name: "default", nodes: "pve-01,pve-02,pve-03,pve-04,pve-05,pve-06,pve-07", comment: "The default HA group, all Proxmox hosts can run the VM."}
