---
mac_bind:
  - {mac_address: "60:be:b4:08:f7:66", nic_name: "enp2lacp0"}
  - {mac_address: "60:be:b4:08:f7:67", nic_name: "enp2lacp1"}
  - {mac_address: "60:be:b4:08:f7:68", nic_name: "enp2lacp2"}
  - {mac_address: "60:be:b4:08:f7:69", nic_name: "enp2lacp3"}

bond0_nic: "enp2lacp0 enp2lacp1 enp2lacp2 enp2lacp3"

wan_management_nic: "bond0"
wan_management_vlan: "3"

wan_management_ip: "192.168.3.2"

cluster_name: "Home"
cluster_vlan: "4"
cluster_ip: "192.168.4.2"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

migration_network: "192.168.4.0/28"

lvm: []

is_ceph_server: true

ceph_devices:
  - {name: "/dev/nvme0n1", type: "nvme"}

ceph_crush_rules:
  - {name: "nvme", type: "nvme"}

ceph_pools:
  - {name: "Ceph_Gold", crush_rule: "nvme", size: 2, min_size: 1}
