---
mac_bind:
  - {mac_address: "00:d0:b4:01:77:7a", nic_name: "enp2lacp0"}
  - {mac_address: "00:d0:b4:01:77:7b", nic_name: "enp2lacp1"}
  - {mac_address: "00:d0:b4:01:77:7c", nic_name: "enp2lacp2"}
  - {mac_address: "00:d0:b4:01:77:7d", nic_name: "enp2lacp3"}

bond0_nic: "enp2lacp0 enp2lacp1"

storage_ip: "10.0.0.2"
storage_netmask: "28"
storage_ip_and_netmask: "{{ storage_ip }}/{{ storage_netmask }}"
storage_nic: "bond0"

wan_management_nic: "enp2lacp2"
wan_management_vlan: "3"

vms_management_nic: "enp2lacp3"

migration_network: "{{ storage_ip_and_netmask }}"

lvm: []

is_ceph_server: true

ceph_devices:
  - {name: "/dev/nvme0n1", type: "nvme"}
