---
mac_bind:
  - {mac_address: "00:e0:0c:a6:70:79", nic_name: "enp1board0"}
  - {mac_address: "00:e0:4c:87:1e:94", nic_name: "enp2lacp0"}
  - {mac_address: "00:e0:4c:87:1e:95", nic_name: "enp2lacp1"}
  - {mac_address: "00:e0:4c:87:1e:96", nic_name: "enp2lacp2"}
  - {mac_address: "00:e0:4c:87:1e:97", nic_name: "enp2lacp3"}
  - {mac_address: "a0:36:9f:40:46:a0", nic_name: "enp3sync0"}
  - {mac_address: "a0:36:9f:40:46:a2", nic_name: "enp3sync1"}

bond0_nic: "enp2lacp0 enp2lacp1 enp2lacp2"
wan_management_nic: "bond0"
wan_management_ip: "{{ ansible_host }}"
wan_management_netmask: "24"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "192.168.0.2"

lan_management_nic: "bond0.1"
lan_management_ip: "10.0.1.10"
lan_management_netmask: "28"
lan_management_ip_and_netmask: "{{ lan_management_ip }}/{{ lan_management_netmask }}"

cluster_nic: "bond0.2"
cluster_ip: "10.0.2.10"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

vms_nic: "bond0.3"

ceph_ip: "10.0.4.10"
ceph_netmask: "28"
ceph_ip_and_netmask: "{{ ceph_ip }}/{{ ceph_netmask }}"

ceph_next_ip_01: "10.0.4.8"
ceph_next_ip_netmask_01: "32"
ceph_next_ip_and_netmask_01: "{{ ceph_next_ip_01 }}/{{ ceph_next_ip_netmask_01 }}"

ceph_next_ip_02: "10.0.4.9"
ceph_next_ip_netmask_02: "32"
ceph_next_ip_and_netmask_02: "{{ ceph_next_ip_02 }}/{{ ceph_next_ip_netmask_02 }}"

lvm: []

is_ceph_server: true
ceph_devices:
  - {name: "/dev/nvme0n1", type: "nvme"}
  - {name: "/dev/nvme1n1", type: "nvme"}
  - {name: "/dev/nvme2n1", type: "nvme"}
  - {name: "/dev/nvme3n1", type: "nvme"}
  - {name: "/dev/sdb", type: "ssd"}
  - {name: "/dev/sdc", type: "ssd"}
  - {name: "/dev/sdd", type: "hdd"}
