---
mac_bind:
  - {mac_address: "00:e0:4c:49:fb:b7", nic_name: "enp1board0"}
  - {mac_address: "00:e0:4c:68:03:b3", nic_name: "enp2lacp0"}
  - {mac_address: "50:e5:49:ac:39:a4", nic_name: "enp2lacp1"}
  - {mac_address: "00:00:00:00:00:05", nic_name: "enp2lacp2"}
  - {mac_address: "94:de:80:8e:ef:45", nic_name: "enp2lacp3"}
  - {mac_address: "a0:36:9f:40:3d:60", nic_name: "enp3sync0"}
  - {mac_address: "a0:36:9f:40:3d:62", nic_name: "enp3sync1"}

bond0_nic: "enp2lacp0 enp2lacp1 enp2lacp2 enp2lacp3"
wan_management_nic: "bond0"
wan_management_ip: "{{ ansible_host }}"
wan_management_netmask: "24"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "192.168.0.2"

lan_management_nic: "bond0.2"
lan_management_ip: "10.0.2.8"
lan_management_netmask: "28"
lan_management_ip_and_netmask: "{{ lan_management_ip }}/{{ lan_management_netmask }}"

cluster_ip: "10.0.3.8"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"
