---
mac_bind:
  - {mac_address: "b4:2e:99:ad:b0:c0", nic_name: "enp1board0"}
  - {mac_address: "a0:36:9f:c8:98:80", nic_name: "enp2lagg0"}
  - {mac_address: "a0:36:9f:c8:98:81", nic_name: "enp3lagg1"}
  - {mac_address: "a0:36:9f:c8:98:82", nic_name: "enp4lagg2"}
  - {mac_address: "a0:36:9f:c8:98:83", nic_name: "enp5sync0"}

template_network_type: "master"

ethtool_command_board0: |-

  post-up /sbin/ethtool -s $IFACE wol g
  post-down /sbin/ethtool -s $IFACE wol g
ethtool_command_sync0: |-

  mtu 9000
bond0_nic: "enp2lagg0 enp3lagg1 enp4lagg2"
wan_management_nic: "enp1board0"
wan_management_ip: "{{ ansible_host }}"
wan_management_netmask: "24"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "192.168.0.2"

lan_management_ip: "10.0.2.5"
lan_management_netmask: "28"
lan_management_ip_and_netmask: "{{ lan_management_ip }}/{{ lan_management_netmask }}"

cluster_management_nic: "enp5sync0"
cluster_ip: "10.0.4.5"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

zfs:
  - {name: "local-zfs-120", mode: "", mountpoint: "/mnt/", compression: "lz4", devices: ["/dev/sda"]}
