---
mac_bind:
  - {mac_address: "00:e0:0b:d9:b0:2c", nic_name: "enp1board0"}

bond0_nic: "enp1board0"
wan_management_nic: "bond0"
wan_management_ip: "{{ ansible_host }}"
wan_management_netmask: "24"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "192.168.0.2"

lan_management_nic: "bond0.2"
lan_management_ip: "10.0.2.11"
lan_management_netmask: "28"
lan_management_ip_and_netmask: "{{ lan_management_ip }}/{{ lan_management_netmask }}"

cluster_ip: "10.0.3.11"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

lvm:
  - { name: "gold_07", logical_volume: "lv_gold", volume_group: "vg_gold", filesystem_type: "ext4", devices: ["/dev/nvme0n1", "/dev/nvme1n1"] }
  - { name: "bronze_07", logical_volume: "lv_bronze", volume_group: "vg_bronze", filesystem_type: "ext4", devices: ["/dev/sdb"] }

is_ceph_server: false
