---
mac_bind:
  - {mac_address: "00:e0:0b:d9:b0:2c", nic_name: "enp1board0"}
  - {mac_address: "a0:36:9f:c8:9c:ac", nic_name: "enp2lacp0"}
  - {mac_address: "a0:36:9f:c8:9c:ad", nic_name: "enp2lacp1"}
  - {mac_address: "a0:36:9f:c8:9c:ae", nic_name: "enp2lacp2"}
  - {mac_address: "a0:36:9f:c8:9c:af", nic_name: "enp2lacp3"}
  - {mac_address: "a0:36:9f:40:53:3c", nic_name: "enp3sync0"}
  - {mac_address: "a0:36:9f:40:53:3e", nic_name: "enp3sync1"}

bond0_nic: "enp2lacp0 enp2lacp1 enp2lacp2"
wan_management_nic: "bond0"
wan_management_vlan: "10"

wan_management_ip: "172.16.10.9"
wan_management_netmask: "28"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "172.16.10.1"

cluster_nic: "enp3sync1"
cluster_ip: "172.16.11.9"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

lvm:
  - { name: "gold_07", logical_volume: "lv_gold", volume_group: "vg_gold", filesystem_type: "ext4", devices: ["/dev/nvme0n1", "/dev/nvme1n1"] }
  - { name: "silver_07", logical_volume: "lv_silver", volume_group: "vg_silver", filesystem_type: "ext4", devices: ["/dev/nvme2n1"] }
  - { name: "bronze_07", logical_volume: "lv_bronze", volume_group: "vg_bronze", filesystem_type: "ext4", devices: ["/dev/sdb"] }

is_ceph_server: false
