---
mac_bind:
  - {mac_address: "b4:2e:99:f4:b8:21", nic_name: "enp1board0"}
  - {mac_address: "00:e0:4c:87:21:ac", nic_name: "enp2lacp0"}
  - {mac_address: "00:e0:4c:87:21:ad", nic_name: "enp2lacp1"}
  - {mac_address: "00:e0:4c:87:21:ae", nic_name: "enp2lacp2"}
  - {mac_address: "00:e0:4c:87:21:af", nic_name: "enp2lacp3"}
  - {mac_address: "a0:36:9f:40:54:78", nic_name: "enp3sync0"}
  - {mac_address: "a0:36:9f:40:54:7a", nic_name: "enp3sync1"}

bond0_nic: "enp2lacp0 enp2lacp1 enp2lacp2 enp2lacp3"
wan_management_nic: "bond0.10"
wan_management_ip: "{{ ansible_host }}"
wan_management_netmask: "28"
wan_management_ip_and_netmask: "{{ wan_management_ip }}/{{ wan_management_netmask }}"
wan_management_gateway: "172.16.10.1"

cluster_nic: "enp3sync1"
cluster_ip: "172.16.11.5"
cluster_netmask: "28"
cluster_ip_and_netmask: "{{ cluster_ip }}/{{ cluster_netmask }}"

lvm: []

is_ceph_server: false
