---
- name: "Installing required packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - { name: "sshpass" }
      - { name: "libsecret-tools" }
      - { name: "python-is-python3" }
      - { name: "pipx" } # A tool for installing and managing Python packages.
      - { name: "python3-passlib" } # Required to use bcrypt.
      - { name: "python3-jmespath" } # Required to use bcrypt.
  notify: "Refreshing ~/.bashrc"

- name: "Flushing all notified handlers at this point"
  ansible.builtin.meta: "flush_handlers"

- name: "Installing pipx packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/pipx"
  vars:
    packages:
      - name: "ansible"
        install_deps: true
      - name: "ansible-lint"
        install_deps: true
      - name: "ansible"
        state: "inject"
        include_injected: true
        inject_packages:
          - "cryptography"
          - "jmespath"
          - "hvac"
          - "certifi"
          - "passlib"
